"""
generate_table.py
=================
Generate a compact LaTeX table of model-pair preference rates
from the Fairness Arena database, ready for AIES/AAAI format.

Usage
-----
    cd analysis
    python generate_table.py [--out results_table.tex]

Output columns: one per recorded session + an Overall column.
Each cell: preference rate for the first (alphabetically canonical) model
           in parentheses with the vote count.
Bold cell = 95% Wilson CI does not include 50% (result distinguishable from chance).
"""

from __future__ import annotations

import argparse
import math
import sqlite3
from pathlib import Path

DB  = Path(__file__).parent.parent / "data" / "arena.db"

# Short display names.  Add entries here as you add models to the arena.
MODEL_NAMES: dict[str, str] = {
    "openai-vitb32": "OpenAI B/32",
    "openai-vitb16": "OpenAI B/16",
    "openai-vitl14": "OpenAI L/14",
    "laion-vitb32":  "LAION B/32",
    # AIES-specific model IDs (if the bundle uses HuggingFace-style IDs)
    "openai/clip-vit-base-patch16":           "CLIP B/16",
    "laion/CLIP-ViT-B-16-laion2B-s34B-b88K": "LAION B/16",
    "google/siglip-base-patch16-224":         "SigLIP",
    "google/siglip2-base-patch16-224":        "SigLIP2",
    "M2_SANER":                               "SANER",
    "M2_NeuralInt":                           "NeuralInt",
    "laion/CLIP-ViT-L-14-laion2B-s32B-b82K": "LAION L/14",
}

def mname(mid: str) -> str:
    return MODEL_NAMES.get(mid, mid)

def norm(ma: str, mb: str) -> tuple[str, str, bool]:
    """Canonical pair: alphabetical order. Returns (ma, mb, flipped)."""
    return (ma, mb, False) if ma <= mb else (mb, ma, True)

def wilson_ci(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    if n == 0:
        return float("nan"), float("nan")
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    m = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return max(0.0, c - m), min(1.0, c + m)


def load_data(db_path: Path) -> tuple[list[dict], list[dict]]:
    con = sqlite3.connect(str(db_path))
    con.row_factory = sqlite3.Row
    sessions = [dict(r) for r in con.execute(
        "SELECT id, name FROM sessions ORDER BY started_at"
    )]
    votes = [dict(r) for r in con.execute(
        "SELECT model_a, model_b, winner, session_id FROM votes"
    )]
    con.close()
    return sessions, votes


def build_tally(votes: list[dict]) -> dict:
    """
    tally[(ma, mb)][session_id | "overall"] = {n_a, n_b, n_tie}
    where (ma, mb) is the canonical pair and n_a = first model preferred.
    """
    from collections import defaultdict
    tally: dict = defaultdict(lambda: defaultdict(lambda: {"n_a": 0, "n_b": 0, "n_tie": 0}))

    for v in votes:
        ma_r, mb_r = v.get("model_a") or "", v.get("model_b") or ""
        if not ma_r or not mb_r:
            continue
        ma, mb, flipped = norm(ma_r, mb_r)
        pk = (ma, mb)

        winner = v.get("winner") or ""
        if flipped and winner in ("A", "B"):
            winner = "B" if winner == "A" else "A"

        bucket = "n_a" if winner == "A" else ("n_b" if winner == "B" else "n_tie")
        tally[pk]["overall"][bucket] += 1
        sid = v.get("session_id")
        if sid:
            tally[pk][sid][bucket] += 1

    return tally


def fmt_cell(counts: dict | None) -> str:
    """Format one table cell: 'XX\% (N)' or '--'."""
    if not counts:
        return "--"
    n = counts["n_a"] + counts["n_b"] + counts["n_tie"]
    if n == 0:
        return "--"
    p_a = counts["n_a"] / n
    lo, hi = wilson_ci(counts["n_a"], n)
    pct = f"{p_a * 100:.0f}\\%"
    significant = (hi < 0.50) or (lo > 0.50)
    cell = f"\\textbf{{{pct}}}" if significant else pct
    return f"{cell} ({n})"


def escape(s: str) -> str:
    """Escape special LaTeX characters in plain-text strings."""
    return s.replace("_", "\\_").replace("&", "\\&").replace("%", "\\%")


def generate_latex(sessions: list[dict], tally: dict) -> str:
    pairs   = sorted(tally.keys())
    col_ids = [s["id"] for s in sessions] + ["overall"]
    col_hdr = [escape(s["name"]) for s in sessions] + ["Overall"]

    ncols    = len(col_ids)
    col_spec = "l" + "r" * ncols

    def row(cells: list[str]) -> str:
        return " & ".join(cells) + r" \\"

    lines: list[str] = []
    lines.append(r"% Auto-generated by analysis/generate_table.py")
    lines.append(r"% Requires: \usepackage{booktabs}")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\small")
    lines.append(r"\setlength{\tabcolsep}{4pt}")
    lines.append(f"\\begin{{tabular}}{{{col_spec}}}")
    lines.append(r"\toprule")

    # Header row
    hdr_cells = ["\\textbf{Model pair}"] + [f"\\textbf{{{h}}}" for h in col_hdr]
    lines.append(row(hdr_cells))
    lines.append(r"\midrule")

    for i, pk in enumerate(pairs):
        ma, mb = pk
        pair_label = f"{escape(mname(ma))} vs {escape(mname(mb))}"
        data_cells = [
            fmt_cell(tally[pk].get(sid))
            for sid in col_ids
        ]
        lines.append(row([pair_label] + data_cells))
        # Thin rule between pairs for readability, except after last
        if i < len(pairs) - 1:
            lines.append(r"\midrule")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(
        r"\caption{Preference rate for the first model in each pair "
        r"across sessions. Values show the percentage of votes where "
        r"the first model was judged fairer, with vote count in parentheses. "
        r"\textbf{Bold}: 95\% Wilson CI excludes 50\% (distinguishable from chance).}"
    )
    lines.append(r"\label{tab:fairness-results}")
    lines.append(r"\end{table}")

    return "\n".join(lines) + "\n"


def main():
    p = argparse.ArgumentParser(description="Generate LaTeX results table")
    p.add_argument("--db",  default=str(DB),   help="Path to arena.db")
    p.add_argument("--out", default="results_table.tex", help="Output .tex file")
    args = p.parse_args()

    sessions, votes = load_data(Path(args.db))
    if not votes:
        print("No votes found in database.")
        return

    tally = build_tally(votes)
    tex   = generate_latex(sessions, tally)

    out = Path(args.out)
    out.write_text(tex, encoding="utf-8")
    print(f"Written -> {out}")
    print()
    print(tex)


if __name__ == "__main__":
    main()
